"""
Django settings for RestApiProject project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""


import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^8ag+cl75j$!soezrs+z-z9mjuz5+iibt))x7*zuu%1@%)i_!t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'admin_soft',  # আপনার লোকাল admin_soft ফোল্ডার থেকে লোড হবে

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',  # CORS ব্যবস্থাপনার জন্য
    'rest_framework',  # Django Rest Framework
    'rest_framework_simplejwt',  # JWT Token Authentication
    'drf_yasg',  # API ডকুমেন্টেশনের জন্য Swagger
    'djoser',  # Djoser কাস্টম ইউজার ম্যানেজমেন্টের জন্য
    'guardian',
    'authentication', # My Authentication App
    'attendance', # Attendance App
    'django_extensions',  # Add this line
    'django_ckeditor_5',
]
# CKEditor 5 File Storage Setup
CKEDITOR_5_FILE_STORAGE = "django.core.files.storage.FileSystemStorage" 
# CKEditor 5 File Upload Path
CKEDITOR_5_UPLOAD_PATH = "uploads/"  

# Custom Color Palette for Tables and Background
customColorPalette = [
    {
        'color': 'hsl(4, 90%, 58%)',
        'label': 'Red'
    },
    {
        'color': 'hsl(340, 82%, 52%)',
        'label': 'Pink'
    },
    {
        'color': 'hsl(291, 64%, 42%)',
        'label': 'Purple'
    },
    {
        'color': 'hsl(262, 52%, 47%)',
        'label': 'Deep Purple'
    },
    {
        'color': 'hsl(231, 48%, 48%)',
        'label': 'Indigo'
    },
    {
        'color': 'hsl(207, 90%, 54%)',
        'label': 'Blue'
    },
    {
        'color': 'hsl(120, 75%, 60%)',
        'label': 'Green'
    },
    {
        'color': 'hsl(60, 90%, 50%)',
        'label': 'Yellow'
    }
]

# CKEditor 5 Configuration
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'heading', '|', 'bold', 'italic', 'link', 'underline', 'strikethrough', 'subscript', 'superscript', 'highlight', 
            '|', 'bulletedList', 'numberedList', 'todoList', '|', 'blockQuote', 'insertTable', 'imageUpload', '|',
            'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', 'mediaEmbed', 'removeFormat', '|',
            'codeBlock', 'sourceEditing', 'outdent', 'indent'
        ],
        'image': {
            'toolbar': ['imageTextAlternative', '|', 'imageStyle:alignLeft', 'imageStyle:alignRight', 'imageStyle:alignCenter', 'imageStyle:side'],
            'styles': ['full', 'side', 'alignLeft', 'alignRight', 'alignCenter']
        },
        'table': {
            'contentToolbar': ['tableColumn', 'tableRow', 'mergeTableCells', 'tableProperties', 'tableCellProperties'],
            'tableProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            },
            'tableCellProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            }
        },
        'list': {
            'properties': {
                'styles': True,  # Allows list styles (e.g., circle, disc, square)
                'startIndex': True,  # Allows lists to start at a specific number
                'reversed': True  # Allows numbered lists to be reversed
            }
        },
        'heading': {
            'options': [
                {'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph'},
                {'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1'},
                {'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2'},
                {'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3'}
            ]
        },
        'mediaEmbed': {
            'previewsInData': True  # Enable media preview in the editor
        },
        'height': 500,  # Editor height
        'width': '100%',  # Editor width
    }
}



AUTH_USER_MODEL = 'authentication.CustomUser'  # আপনার অ্যাপের নাম দিয়ে 'your_app_name' রিপ্লেস করুন 

LANGUAGE_CODE = 'en-us'  # Default language
TIME_ZONE = 'Asia/Dhaka'
USE_TZ = True

USE_I18N = True  # Enable internationalization (i18n)
USE_L10N = True  # Enable localization (l10n)

LANGUAGES = [
    ('en', 'English'),
    ('bn', 'Bengali'),
    ('hi', 'Hindi'),
    ('zh', 'Chinese'),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),  # Global locale directory if translations are global
    os.path.join(BASE_DIR, 'attendance', 'locale'),  # App-specific locale directory
]

# Celery Configuration Options
CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Redis URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_BACKEND = None  # আমরা রেজাল্ট ব্যাকএন্ড ব্যবহার করছি না

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # CORS Middleware
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise Middleware যোগ করুন

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',


]

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',  # Django এর ডিফল্ট ব্যাকএন্ড
    'guardian.backends.ObjectPermissionBackend',  # Guardian এর ব্যাকএন্ড
)
ANONYMOUS_USER_ID = -1  # অ্যাননিমাস ইউজার আইডি সেট করা হচ্ছে

# RestApiProject/settings.py

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # সব API-তে অটেনটিকেশন আবশ্যক
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # JWT টোকেন ব্যবহৃত হবে
        'rest_framework.authentication.SessionAuthentication',  # সেশন ব্যবহৃত হবে
    ),

    'DEFAULT_THROTTLE_RATES': {
        'user': '100/day',  # Limit authenticated users to 100 requests per day
        'anon': '10/hour',  # Limit unauthenticated users to 10 requests per hour
    }
}

# JWT Token-এর সময়সীমা নির্ধারণ
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=240),  # JWT Access Token এর সময়সীমা
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),  # JWT Refresh Token এর সময়সীমা
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
}






# Add the following if not already present
LOGIN_URL = 'login'  # Redirect to login if not logged in
LOGOUT_URL = 'logout'  # Redirect to logout
LOGIN_REDIRECT_URL = '/'  # Redirect after login
LOGOUT_REDIRECT_URL = 'home'  # Redirect after logout

# RestApiProject/settings.py

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # SMTP ব্যবহার
EMAIL_HOST = 'business39.web-hosting.com'  # আপনার SMTP সার্ভারের ঠিকানা
EMAIL_PORT = 465  # SSL এর জন্য পোর্ট
EMAIL_USE_SSL = True  # SSL এনক্রিপশন সক্রিয়
EMAIL_HOST_USER = 'olee@kreatech.ca'  # আপনার ইমেল অ্যাড্রেস
EMAIL_HOST_PASSWORD = 'olee@kreatech'  # ইমেলের পাসওয়ার্ড
DEFAULT_FROM_EMAIL = 'olee@kreatech.ca'  # ডিফল্ট প্রেরক ইমেল

CORS_ALLOW_ALL_ORIGINS = True  # সব উত্সকে অনুমতি দেওয়া
# CORS_ALLOWED_ORIGINS = [

# 'http://127.0.0.1:4000',

# ] # Add other allowed origins as needed



ROOT_URLCONF = 'RestApiProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'admin_soft.context_processors.languages',  # <- Update this line
                'attendance.context_processors.languages',  # <- Update this line


            ],
        },
    },
]

WSGI_APPLICATION = 'RestApiProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'django',
#         'USER': 'root',
#         'PASSWORD': '',
#         'HOST':'localhost',
#         'PORT':'3306',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Add this line
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# You might also want to ensure you have these settings
STATIC_URL = '/static/'

# Media Configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
# Additional settings for static files if necessary
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # where your static files are during development
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field
# WhiteNoise settings
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
