# Generated by Django 5.1.1 on 2024-09-24 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='contact_number',
            new_name='mobileNo',
        ),
    ]
