# Generated by Django 5.0.6 on 2024-09-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_company_customuser_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_company_active',
            field=models.BooleanField(default=True),
        ),
    ]
