# Generated by Django 5.0.6 on 2024-09-26 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='authentication.company'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.device'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedule',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.employee'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.shift'),
        ),
        migrations.AddField(
            model_name='workhours',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.employee'),
        ),
        migrations.AddConstraint(
            model_name='attendancelog',
            constraint=models.UniqueConstraint(fields=('employee', 'timestamp'), name='unique_attendance_log_per_user_per_day_per_checkin'),
        ),
    ]
